version: '3'
services:
  backend:
    build:
      context: .
      ports:
      - "3001:3001"
      - "8545:8545"
  frontend:
    build:
      context: ./blockchain_frontend
      ports: 
        - "3006:3000"
